import json
from collections import defaultdict
from typing import List, Dict, Optional

from skin import Skin

class JSON_Storage:
    """
    Stores Skin objects and writes to JSON files
    Can also read in JSON files to create a list of skin objects
    """

    def __init__(self, json_objects: Optional[List[Skin]] = None):
        # Key structure:
        # self.data[champion][skin_name] = skin
        self.data = defaultdict(dict)

        if json_objects:
            for obj in json_objects:
                champion = obj.Champion
                skin_name = obj.Skin_Name
                if champion and skin_name:
                    self.data[champion][skin_name] = obj

    def add_skin(self, skin_obj: Skin):
        """Add a new skin, overwrite if it already exists."""
        champ = skin_obj.Champion
        name = skin_obj.Skin_Name
        self.data[champ][name] = skin_obj

    def delete_skin(self, champion: str, skin_name: str) -> bool:
        """Delete a skin. Returns True if deletion occurred."""
        if champion in self.data and skin_name in self.data[champion]:
            del self.data[champion][skin_name]
            if not self.data[champion]:
                del self.data[champion]
            return True
        return False

    def update_skin(self, champion: str, skin_name: str, new_data: Skin) -> bool:
        """Overwrite the skin if it exists."""
        if self.exists(champion, skin_name):
            self.data[champion][skin_name] = new_data
            return True
        return False

    def exists(self, champion: str, skin_name: str) -> bool:
        return skin_name in self.data.get(champion, {})

    # ------------------------------
    # RETRIEVAL
    # ------------------------------

    def get_skin(self, champion: str, skin_name: str) -> Optional[Skin]:
        return self.data.get(champion, {}).get(skin_name, None)

    def get_skins_by_champion(self, champion: str) -> List[Skin]:
        return list(self.data.get(champion, {}).values())

    def get_all_skins(self) -> List[Skin]:
        skins = []
        for champ in self.data:
            skins.extend(self.data[champ].values())
        return skins

    def get_by_skin_name_global(self, skin_name: str) -> List[Skin]:
        """
        Returns a list of all skins a champion has
        """
        results = []
        for champ in self.data.values():
            if skin_name in champ:
                results.append(champ[skin_name])
        return results

    # ------------------------------
    # DIFFERENCE CHECKING
    # ------------------------------

    def diff(self, old: Skin, new: Skin) -> Dict:
        """
        Compare two skins
        Returns only differences
        """
        old_data = old.skin_data
        new_data = new.skin_data
        changed = {}
        for key in old_data:
            if old_data[key] != new_data[key]:
                changed[key] = {"old": old_data[key], "new": new_data[key]}
        return changed

    # ------------------------------
    # EXPORT / IMPORT
    # ------------------------------

    def to_flat_json(self, filepath: str):
        """
        Save to flattened JSON file.
        """
        with open(filepath, "w", encoding="utf-8") as f:
            flat_list = self.get_all_skins()
            flat_list = [skin.skin_data for skin in flat_list]
            json.dump(flat_list, f, indent=4, ensure_ascii=False)


    def to_champ_json(self, filepath: str):
        """Save to JSON file sorted by champion."""
        with open(filepath, "w", encoding="utf-8") as f:
            full_dict = {champ: [s.skin_data for s in self.data[champ].values()] for champ in self.data}
            json.dump(full_dict, f, indent=4, ensure_ascii=False)

    @staticmethod
    def from_flat_json(filepath: str):
        """
        Load from a JSON file generated by to_flat_json().
        Reconstructs full Skin objects, inserts them into storage,
        and returns a JSON_Storage instance.
        """
        with open(filepath, "r", encoding="utf-8") as f:
            raw = json.load(f)

        # raw is a list of dictionaries → convert to Skin objects
        skin_objects = [Skin(skin_dict) for skin_dict in raw]

        return JSON_Storage(skin_objects)

    @staticmethod
    def from_champ_json(filepath: str):
        """
        Load from a JSON file generated by to_champ_json().
        Reconstructs full Skin objects, inserts them into storage,
        and returns a JSON_Storage instance.
        """
        with open(filepath, "r", encoding="utf-8") as f:
            raw = json.load(f)
        skin_objects = []

        for champ, skins in raw.items():
            for skin_dict in skins:
                skin_objects.append(Skin(skin_dict))

        return JSON_Storage(skin_objects)

    def export_for_static_site(self) -> Dict:
        """
        Returns a JSON object safe to serve on GitHub Pages.
        Format:
        {
            "Ahri": { "Foxfire": {...}, ... },
            "Lux": { "Elementalist": {...} }
        }
        (This is ideal for JS to iterate through.)
        """
        return {champ: [s.skin_data for s in self.data[champ].values()] for champ in self.data}
